### ISSUE TITLE
Required does not work for int argument type.

### ISSUE THREAD

**Issue by SeanMeyer** [BizArk/BizArk3#7]
Following how required is implemented in the Wiki (using `[Required]`) does not work for `int` types. I believe this is because the value of an `int` is 0, as if I use an `int?` type it works (but then of course I get a different type shown in the help screen).

**Comment by bbrewder** [comment]
Thanks for reporting this. Currently, as you have probably guessed, the code is using DataAnnotations to perform validation logic. This library assumes Required means that the property has a non-null value. and has no other logic beyond that.

I see two ways to fix this. 

1. Redefine what Required means so that the argument must be specified on the command-line and be, non-empty (standard DataAnnotation behavior).

2. Create a new attribute that means the command-line argument must be specified (could be empty - that's for Required to deal with that).

#2 would probably be most "correct". It allows Required to work the way it is meant to work (checking for empty values) as opposed to meaning the argument must be specified. It would also mean that you could have a command-line argument that must be specified, but can be empty (of course, ints, cannot be empty since all values are potentially valid).

However, I am sort of leaning towards #1 at the moment. It seems more intuitive. You assumed it worked this way (granted, the documentation was a bit mis-leading) and I had to look up the code to verify that it didn't work this way. Theoretically I can imagine a scenario where a value must be specified but can be empty, but I can't think of any actual scenarios where this would be useful.

I'm going to let this simmer for at least a couple days to consider which direction I want to go. I'm open to other ideas or arguments for/against either option.

**Comment by bbrewder** [comment]
I went with the first option. Placing a RequiredAttribute on a property will make that field required in the command-line arguments passed in. This is now available in NuGet (https://www.nuget.org/packages/BizArk.ConsoleApp/3.1.0.19).
