### ISSUE TITLE
Versions available on Nuget.org

### ISSUE THREAD

**Issue by jazmatician** [BizArk/BizArk3#9]
Attempted to start a new project with the v4 version of the console app functionality, I have been using the v3 binaries for a few months, but didn't want to worry about upgrading existing projects. I attempted to add the latest 4.0.1.50 version of BizArk.ConsoleApp, but it failed because it requires the same version of BizArk.Core, but the most recent version available publicly is 4.0.0.45.
For now, I can install the build 45 version of the ConsoleApp, but wanted to get any bug fixes while I'm making the leap.
Thanks for the active development on this project.

**Comment by bbrewder** [comment]
Sorry it took so long to get back to this, work was crazy busy when you posted this. I think the problem is that Appveyor only publishes the package for the project that was modified. Unfortunately, as you found out the hard way, the version for the required package was updated.

Anyway, I uploaded the latest packages to Nuget.org. Hopefully this solves the problem.

**Comment by jazmatician** [comment]
Thanks, looks good now!
